spring:
  application:
    name: mybank

  datasource:
    url: jdbc:postgresql://localhost:5432/mybank
    username: postgres
    password: postgres

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true